---

codecov:
  notify:
    after_n_builds: 24  # The number of test matrix+lint jobs uploading coverage
    wait_for_ci: false

  require_ci_to_pass: false

  token: 26f4a393-24a9-48d9-8fa4-f1344d930846  # repo-scoped

comment:
  require_changes: true

coverage:
  range: 99.34..100
  status:
    project:
      default:
        target: 100%
      lib:
        paths:
        - yarl/
        target: 97.83%
      tests:
        paths:
        - tests/
        target: 100%

...
