[tox]
envlist = python
isolated_build = true
minversion = 4.22
requires =
  tox-uv >= 1.20


[python-cli-options]
byte-warnings = -b
byte-errors = -bb
max-isolation = -E -s -I
some-isolation = -E -s
warnings-to-errors = -Werror


[testenv]
description =
  Run the project test suite under {basepython}
package = wheel
extras =
deps =
  -r requirements/codspeed.txt
commands_pre =
  {envpython} \
    {[python-cli-options]byte-errors} \
    {[python-cli-options]max-isolation} \
    {[python-cli-options]warnings-to-errors} \
    -c \
      'import sys; \
      print(sys.version_info); \
      print(sys.executable);'
commands =
  {envpython} \
    {[python-cli-options]byte-warnings} \
    {[python-cli-options]some-isolation} \
    -m pytest \
      {tty:--color=yes} \
      {posargs:}


[dists]
setenv =
  PIP_CONSTRAINT = {toxinidir}{/}requirements{/}cython.txt


[testenv:cleanup-dists]
description =
  Wipe the the `{env:PEP517_OUT_DIR}{/}` folder
package = skip
deps =
setenv =
  {[dists]setenv}
  PEP517_OUT_DIR = {env:PEP517_OUT_DIR:{toxinidir}{/}dist}
commands_pre =
commands =
  {envpython} \
    {[python-cli-options]byte-errors} \
    {[python-cli-options]max-isolation} \
    {[python-cli-options]warnings-to-errors} \
    -c \
      'import os, shutil, sys; \
      dists_dir = "{env:PEP517_OUT_DIR}{/}"; \
      shutil.rmtree(dists_dir, ignore_errors=True); \
      sys.exit(os.path.exists(dists_dir))'


[testenv:build-dists]
description =
  Build dists with {basepython} and put them into the
  `{env:PEP517_OUT_DIR}{/}` folder
depends =
  cleanup-dists
# NOTE: The custom command is invoked through `build`, which uses
# NOTE: PEP 517 to delegate the actual build to `pep517_backend.hooks`
# NOTE: living under `packaging/`.
package = skip
deps =
  build ~= 1.2.2
setenv =
  {[dists]setenv}
  PEP517_BUILD_ARGS = --config-setting=pure-python=true
  PEP517_OUT_DIR = {env:PEP517_OUT_DIR:{toxinidir}{/}dist}
commands_pre =
commands =
  {envpython} \
    {[python-cli-options]byte-errors} \
    {[python-cli-options]max-isolation} \
    {[python-cli-options]warnings-to-errors} \
    -m build \
      --outdir '{env:PEP517_OUT_DIR}{/}' \
      {posargs:{env:PEP517_BUILD_ARGS}} \
      '{toxinidir}'


[testenv:metadata-validation]
description =
  Verify that dists under the `{env:PEP517_OUT_DIR:dist}{/}` dir
  have valid metadata
depends =
  build-dists
package = skip
deps =
  twine ~= 6.0
setenv =
  PEP517_OUT_DIR = {env:PEP517_OUT_DIR:{toxinidir}{/}dist}
commands_pre =
commands =
  {envpython} \
    {[python-cli-options]byte-errors} \
    {[python-cli-options]max-isolation} \
    {[python-cli-options]warnings-to-errors} \
    -m twine \
      check \
      --strict \
      {env:PEP517_OUT_DIR}{/}*


[testenv:pre-commit]
description =
  Run the pre-commit-managed linter hooks against the repo
package = skip
deps =
  -r requirements/lint.txt
setenv =
  PRE_COMMIT_COLOR = always
commands_pre =
commands =
  {envpython} \
    {[python-cli-options]byte-warnings} \
    {[python-cli-options]some-isolation} \
    -m pre_commit \
      run \
      --all-files \
      --show-diff-on-failure \
      {posargs:}


[testenv:build-docs]
description =
  Build the documentation under `docs{/}_build{/}html`
package = skip
deps =
  -r requirements/doc.txt
allowlist_externals =
  make
commands_pre =
commands =
  make -C docs html SPHINXOPTS="-W -E --keep-going -n"


[testenv:doctest-docs]
description =
  Run the doctests embedded in the documentation
package = skip
deps =
  -r requirements/doc.txt
allowlist_externals =
  make
commands_pre =
commands =
  make -C docs doctest SPHINXOPTS="-W -E --keep-going -n"


[testenv:spellcheck-docs]
description =
  Spell-check the documentation
platform = darwin|linux
package = skip
deps =
  -r requirements/doc-spelling.txt
allowlist_externals =
  make
commands_pre =
commands =
  make -C docs spelling SPHINXOPTS="-W -E --keep-going -n"
