---
name: 🐞 Bug Report
description: Create a report to help us improve.
labels:
- bug
body:
- type: markdown
  attributes:
    value: |
      **Thanks for taking a minute to file a bug report!**

      ⚠
      Verify first that your issue is not [already reported on
      GitHub][issue search].

      _Please fill out the form below with as many precise
      details as possible._

      [issue search]: ../search?q=is%3Aissue&type=issues

- type: checkboxes
  id: terms
  attributes:
    label: Please confirm the following
    description: |
      Read the [aio-libs Code of Conduct][CoC] first. Check the existing issues
      on the tracker. Take into account the possibility of your report
      surfacing a security vulnerability.

      [CoC]: ../../.github/blob/master/CODE_OF_CONDUCT.md
    options:
    - label: |
        I agree to follow the [aio-libs Code of Conduct][CoC]

        [CoC]: ../../.github/blob/master/CODE_OF_CONDUCT.md
      required: true
    - label: |
        I have checked the [current issues][issue search] for duplicates.

        [issue search]: ../search?q=is%3Aissue&type=issues
      required: true
    - label: >-
        I understand this is open source software provided for free and
        that I might not receive a timely response.
      required: true
    - label: |
        I am positive I am **NOT** reporting a (potential) security
        vulnerability, to the best of my knowledge. *(These must be shared by
        submitting [this report form][vulnerability report form] instead, if
        any hesitation exists.)*

        [vulnerability report form]: ../security/advisories/new
      required: true
    - label: >-
        I am willing to submit a pull request with reporoducers as xfailing test
        cases or even entire fix. *(Assign this issue to me.)*
      required: false

- type: textarea
  attributes:
    label: Describe the bug
    description: >-
      A clear and concise description of what the bug is.
  validations:
    required: true

- type: textarea
  attributes:
    label: To Reproduce
    description: >-
      Describe the steps to reproduce this bug.
    placeholder: |
      1. Have certain environment
      2. Run given code snippet in a certain way
      3. See some behavior described
  validations:
    required: true

- type: textarea
  attributes:
    label: Expected behavior
    description: >-
      A clear and concise description of what you expected to happen.
  validations:
    required: true

- type: textarea
  attributes:
    label: Logs/tracebacks
    description: |
      If applicable, add logs/tracebacks to help explain your problem.
      Paste the output of the steps above, including the commands
      themselves and their output/traceback etc.
    render: python-traceback
  validations:
    required: true

- type: textarea
  attributes:
    label: Python Version
    description: Attach your version of Python.
    render: console
    value: |
      $ python --version
  validations:
    required: true
- type: textarea
  attributes:
    label: multidict Version
    description: Attach your version of multidict.
    render: console
    value: |
      $ python -m pip show multidict
  validations:
    required: true
- type: textarea
  attributes:
    label: propcache Version
    description: Attach your version of propcache.
    render: console
    value: |
      $ python -m pip show propcache
  validations:
    required: true
- type: textarea
  attributes:
    label: yarl Version
    description: Attach your version of yarl.
    render: console
    value: |
      $ python -m pip show yarl
  validations:
    required: true

- type: textarea
  attributes:
    label: OS
    placeholder: >-
      For example, Arch Linux, Windows, macOS, etc.
  validations:
    required: true

- type: textarea
  attributes:
    label: Additional context
    description: |
      Add any other context about the problem here.

      Describe the environment you have that lead to your issue.
      This includes proxy server and other bits that are related to your case.

...
