trigger:
  batch: true
  branches:
    include:
    - master
    exclude:
    - refs/tags/*
pr:
  autoCancel: true
  branches:
    include:
    - master

variables:
- group: codecov

stages:
- stage: lint
  displayName: 'Run linters'
  jobs:
  - template: linters-template.yml
- stage: test
  displayName: 'Run tests'
  jobs:
  - template: tests-template.yml
    parameters:
      codecov.token: '$(codecov.token)'
