parameters:
  steps: []
  python: '3.7'
  architecture: ''
  artifact: dist
  distfolder: ''

steps:                            
  - checkout: self
    submodules: true
    clean: true

  - task: UsePythonVersion@0
    inputs:
      versionSpec: ${{ parameters.python }}
      ${{ if ne(parameters.architecture, '') }}:
        architecture: ${{ parameters.architecture }}

  - script: |
      pip install -U setuptools wheel
    displayName: 'Install tools'

  - ${{ parameters.steps }}                # Users steps

  - template: step-store-dist.yml
    parameters:
      artifact: ${{ parameters.artifact }}
      folder: ${{ coalesce(parameters.distfolder, '$(Build.SourcesDirectory)/dist') }}
