parameters:
  artifact: dist
  folder: $(Build.SourcesDirectory)/dist

steps:
- task: CopyFiles@2
  displayName: 'Copy distribution'
  inputs:
    sourceFolder: ${{ parameters.folder }}
    targetFolder: $(Build.ArtifactStagingDirectory)
- task: PublishBuildArtifacts@1
  displayName: 'Publish distribution'
  inputs:
    pathtoPublish: $(Build.ArtifactStagingDirectory)
    artifactName: ${{ parameters.artifact }}
